optimizer:
  name: "adamw"
  lr: !!float 3e-4
  weight_decay: !!float 1e-6

lr_scheduler:
  # name: 'multi_step'
  # milestones: [400, 800]
  # gamma: 0.1
  name: "identity"

max_norm: null

path:
  # train_path: '/Data2/DataSet/HISR/CAVE/train_cave(with_up)x4.h5'
  # val_path: '/Data2/DataSet/HISR/CAVE/validation_cave(with_up)x4.h5'
  #   train_path: '/media/office-401-remote/Elements SE/cao/ZiHanCao/datasets/pansharpening/wv3/training_wv3/train_wv3.h5'
  #   val_path: '/media/office-401-remote/Elements SE/cao/ZiHanCao/datasets/pansharpening/wv3/reduced_examples/test_wv3_multiExm1.h5'
  # train_path: '/media/office-401-remote/Elements SE/cao/ZiHanCao/datasets/pansharpening/gf/training_gf2/train_gf2.h5'
  # val_path: '/media/office-401-remote/Elements SE/cao/ZiHanCao/datasets/pansharpening/gf/training_gf2/valid_gf2.h5'
  #   train_path: '/media/office-401-remote/Elements SE/cao/ZiHanCao/datasets/pansharpening/qb/training_qb/train_qb.h5'
  #   val_path: '/media/office-401-remote/Elements SE/cao/ZiHanCao/datasets/pansharpening/qb/training_qb/valid_qb.h5'
  # train_path: "/Data2/ZiHanCao/datasets/pansharpening/gf/training_gf2/train_gf2.h5"
  # val_path: "/Data2/ZiHanCao/datasets/pansharpening/gf/training_gf2/valid_gf2.h5"

  train_path: "/Data2/ZiHanCao/datasets/pansharpening/qb/reduced_examples/test_qb_multiExm1.h5"
  val_path: "/Data2/ZiHanCao/datasets/pansharpening/qb/reduced_examples/test_qb_multiExm1.h5"

  # train_path: '/media/office-401-remote/Elements SE/cao/ZiHanCao/datasets/pansharpening/wv3/reduced_examples/test_wv3_multiExm1.h5'
  # val_path: '/media/office-401-remote/Elements SE/cao/ZiHanCao/datasets/pansharpening/wv3/reduced_examples/test_wv3_multiExm1.h5'
  # train_path: '/media/office-401-remote/Elements SE/cao/ZiHanCao/datasets/pansharpening/gf/reduced_examples/test_gf2_multiExm1.h5'
  # val_path: '/media/office-401-remote/Elements SE/cao/ZiHanCao/datasets/pansharpening/gf/reduced_examples/test_gf2_multiExm1.h5'
#   train_path: '/media/office-401-remote/Elements SE/cao/ZiHanCao/datasets/pansharpening/qb/reduced_examples/test_qb_multiExm1.h5'
#   val_path: '/media/office-401-remote/Elements SE/cao/ZiHanCao/datasets/pansharpening/qb/reduced_examples/test_qb_multiExm1.h5'

#  train_path: '/home/ZiHanCao/datasets/pansharpening/gf/training_gf2/train_gf2.h5'
#  val_path: '/home/ZiHanCao/datasets/pansharpening/gf/training_gf2/valid_gf2.h5'
#  train_path: '/home/ZiHanCao/datasets/pansharpening/qb/training_qb/train_qb.h5'
#  val_path: '/home/ZiHanCao/datasets/pansharpening/qb/training_qb/valid_qb.h5'

#   train_path: "/media/office-401-remote/Elements SE/cao/ZiHanCao/datasets/HISI/new_cave/train_cave(with_up)x4.h5"
#   val_path: "/media/office-401-remote/Elements SE/cao/cavex4/test_cavepatches64-2.h5"

#  train_path: "/home/ShangqiDeng/data/HSI/cave_x8/train_cave(with_up)x8_rgb.h5"
#  val_path: "/home/ZiHanCao/datasets/HISI/new_cave/x8/validation_cave(with_up)x8_rgb.h5"

# train_path: "/home/ShangqiDeng/data/HSI/cave_x8/train_cave(with_up)x8_rgb_16.h5"
# val_path: "/home/ShangqiDeng/data/HSI/cave_x8/test_cavepatches128-2.h5"

# train_path: "/Data2/ZiHanCao/datasets/HISI/new_harvard/x8/train_harvard(with_up)x8_rgb.h5"
# val_path: "/Data2/ZiHanCao/datasets/HISI/new_harvard/x8/test_clip_128.h5"

#   train_path: '/home/ZiHanCao/datasets/HISI/new_harvard/train_harvard(with_up)x4_rgb.h5'
#   val_path: '/home/ZiHanCao/datasets/HISI/new_harvard/validation_harvard(with_up)x4_rgb.h5'

network_configs:
  ms_inp_ch: 4
  num_layers: 4
  latent_dim: 64

logger_config:
  base_path: ./log_file/
  name: pmacnet
  file_mode: w
