optimizer:
  name: "adamw"
  lr: !!float 1e-3
  weight_decay: !!float 1e-6

lr_scheduler:
  name: "multi_step"
  milestones: [400, 800]
  gamma: 0.1

max_norm: 0.01

path:
  #  train_path: '/Data2/DataSet/HISR/CAVE/train_cave(with_up)x4.h5'
  #  val_path: '/Data2/DataSet/HISR/CAVE/validation_cave(with_up)x4.h5'
  train_path: "/Data2/ZiHanCao/datasets/pansharpening/GF5-GF1/tap23/train_GF5_GF1_23tap_new.h5"
  val_path: "/Data2/ZiHanCao/datasets/pansharpening/GF5-GF1/tap23/test_GF5_GF1_23tap_new.h5"

#  train_path: '/home/ZiHanCao/datasets/HISI/new_cave/train_cave(with_up)x4.h5'
#  val_path: '/home/ZiHanCao/datasets/HISI/new_cave/validation_cave(with_up)x4.h5'
#  train_path: '/home/ZiHanCao/datasets/HISI/new_harvard/train_harvard(with_up)x4_rgb.h5'
#  val_path: '/home/ZiHanCao/datasets/HISI/new_harvard/validation_harvard(with_up)x4_rgb.h5'

network_configs:
  arch: "SSRNET"
  n_bands: 150
  rgb_channel: 4
  scale_ratio: 2

logger_config:
  base_path: ./log_file/
  name: ssrnet_gf5
  file_mode: w
