optimizer:
  name: 'adamw'
  lr: !!float 1e-4
  weight_decay: !!float 1e-6

lr_scheduler:
  name: 'multi_step'
  milestones: [300, 600, 1000]
  gamma: 0.1
#  name: 'identity'

max_norm: null

path:
#   train_path: '/home/ZiHanCao/datasets/pansharpening/wv3/training_wv3/train_wv3.h5'
#   val_path: '/home/ZiHanCao/datasets/pansharpening/wv3/training_wv3/valid_wv3.h5'
#   train_path: "/home/ZiHanCao/datasets/HISI/new_cave/train_cave(with_up)x4.h5"
#   val_path: "/home/ShangqiDeng/data/HSI/cave_x4/test_cavepatches64-2.h5"
#   train_path: '/home/ZiHanCao/datasets/pansharpening/qb/training_qb/train_qb.h5'
#   val_path: '/home/ZiHanCao/datasets/pansharpening/qb/training_qb/valid_qb.h5'
#  train_path: '/home/ZiHanCao/datasets/pansharpening/gf/training_gf2/train_gf2.h5'
#  val_path: '/home/ZiHanCao/datasets/pansharpening/gf/training_gf2/valid_gf2.h5'

    base_dir: "/Data2/ZiHanCao/datasets/RoadScene_and_TNO/"

network_configs:
  in_channel: 1
  out_channel: 64
  output_channel: 1
  img_size: 128


logger_config:
  base_path: ./log_file/
  name: dcfnet
  file_mode: w